########################################################################################################################
# Deployment. Elasticsearch
########################################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: st-elasticsearch
  name: st-elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: st-elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: st-elasticsearch
    spec:
      containers:
      - image: localhost:5000/st-elasticsearch
        imagePullPolicy: Always
        name: st-elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      imagePullSecrets:
        - name: stashregistry
      dnsPolicy: ClusterFirst
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
########################################################################################################################
# Service.  Elasticsearch
########################################################################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    run: st-elasticsearch
  name: st-elasticsearch
  namespace: default
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    run: st-elasticsearch
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: st-elasticsearch-cluster
  name: st-elasticsearch-cluster
  namespace: default
spec:
  ports:
  - port: 9300
    targetPort: 9300
  selector:
    run: st-elasticsearch
  sessionAffinity: None
  type: LoadBalancer
